### ISSUE TITLE
PHP7.2.20+swoole 4.4.0 Swoole\Server::getClientInfo

### ISSUE THREAD

**Issue by getchu** [cabalphp/skeleton#12]
./bin/cabal start
Starting CabalServerServer@ is started at http://0.0.0.0:9501
2019-07-09 01:30:32 示例任务执行成功
2019-07-09 01:30:32 示例任务回调执行成功 vars: ["5d237db87822d"]
2019-07-09 01:30:32 tasker 进程启动
2019-07-09 01:30:32 示例任务执行成功
2019-07-09 01:30:33 示例任务回调执行成功 vars: ["5d237db978a16"]
PHP Fatal error:  Couldn't find implementation for method Swoole\Server::getClientInfo in Unknown on line 0
2019-07-09 01:30:36 示例任务执行成功
2019-07-09 01:30:37 示例任务回调执行成功 vars: ["5d237dbd6377b"]

**Comment by getchu** [comment]
访问Demo主页, 立即报出 PHP Fatal error: Couldn't find implementation for method Swoole\Server::getClientInfo in Unknown on line 0



# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0
Built => Jul  8 2019 20:29:12
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by keefe-wu** [comment]
建议使用 https://hyperf.io 框架哈
